openapi: 3.0.0
info:
  title: admissions-application-checklist
  description: API for SAAADMS administrative page
  version: 1.0.0
  x-source-name: SAAADMS
  x-source-title: Admissions Application Form
  x-source-system: Banner
  x-api-type: Administrative
servers:
- url: https://integrate.elluciancloud.com
  description: Ethos Integration API U.S.
- url: https://integrate.elluciancloud.ca
  description: Ethos Integration API Canada
- url: https://integrate.elluciancloud.com
  description: Ethos Integration API Europe
- url: https://integrate.elluciancloud.com.au
  description: Ethos Integration API Asia-Pacific
paths:
  /api/admissions-application-checklist:
    get:
      tags:
      - admissions-application-checklist
      summary: Return resources from SAAADMS
      parameters:
      - name: limit
        in: query
        description: The maximum number of resources requesting for this result set.
        required: false
        schema:
          type: integer
      - name: offset
        in: query
        description: The 0 based index for a collection of resources for the page
          requested.
        required: false
        schema:
          type: integer
      - name: criteria
        in: query
        description: The filter criteria. Must be a JSON representation of the property
          searching for.  This can be any of the properties listed on the URL or QAPI
          and must be a json representation that can be validated against the GET
          schema.
        required: false
        schema:
          type: string
      - name: X-SDE-Expand
        in: header
        description: The comma seperated value list of block names
        required: false
        schema:
          type: string
      - name: id
        in: query
        required: false
        schema:
          type: string
      - name: kbentryTermCode
        in: query
        required: false
        schema:
          type: string
      responses:
        '200':
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response
                body is associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/admissions-application-checklist-1.0.0_get'
        '401':
          description: Failure. Unauthorized
        '500':
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/errors-2.0.0'
    put:
      tags:
      - admissions-application-checklist
      summary: Updates an existing resource in SAAADMS
      parameters:
      - name: limit
        in: query
        description: The maximum number of resources requesting for this result set.
        required: false
        schema:
          type: integer
      - name: offset
        in: query
        description: The 0 based index for a collection of resources for the page
          requested.
        required: false
        schema:
          type: integer
      - name: criteria
        in: query
        description: The filter criteria. Must be a JSON representation of the property
          searching for.  This can be any of the properties listed on the URL or QAPI
          and must be a json representation that can be validated against the GET
          schema.
        required: false
        schema:
          type: string
      - name: X-SDE-Expand
        in: header
        description: The comma seperated value list of block names
        required: false
        schema:
          type: string
      - name: id
        in: query
        required: false
        schema:
          type: string
      - name: kbentryTermCode
        in: query
        required: false
        schema:
          type: string
      - name: criteria.admrCode
        in: query
        required: false
        schema:
          type: string
      - name: criteria.stvadmrDesc
        in: query
        required: false
        schema:
          type: string
      - name: criteria.receiveDate
        in: query
        required: false
        schema:
          type: string
      - name: criteria.codeValue
        in: query
        required: false
        schema:
          type: string
      - name: criteria.comment
        in: query
        required: false
        schema:
          type: string
      - name: criteria.mandatoryInd
        in: query
        required: false
        schema:
          type: string
      - name: criteria.printInd
        in: query
        required: false
        schema:
          type: string
      - name: criteria.reqDate1
        in: query
        required: false
        schema:
          type: string
      - name: criteria.reqDate2
        in: query
        required: false
        schema:
          type: string
      - name: criteria.reqCount
        in: query
        required: false
        schema:
          type: string
      - name: criteria.source
        in: query
        required: false
        schema:
          type: string
      - name: criteria.sourceDate
        in: query
        required: false
        schema:
          type: string
      - name: criteria.deadlineDate
        in: query
        required: false
        schema:
          type: string
      - name: criteria.cksrCode
        in: query
        required: false
        schema:
          type: string
      - name: criteria.ckstCode
        in: query
        required: false
        schema:
          type: string
      - name: receiveDate
        in: query
        required: false
        schema:
          type: string
      - name: codeValue
        in: query
        required: false
        schema:
          type: string
      - name: comment
        in: query
        required: false
        schema:
          type: string
      - name: mandatoryInd
        in: query
        required: false
        schema:
          type: string
      - name: printInd
        in: query
        required: false
        schema:
          type: string
      - name: reqDate1
        in: query
        required: false
        schema:
          type: string
      - name: reqDate2
        in: query
        required: false
        schema:
          type: string
      - name: deadlineDate
        in: query
        required: false
        schema:
          type: string
      - name: ckstCode
        in: query
        required: false
        schema:
          type: string
      - name: admrCode
        in: query
        required: false
        schema:
          type: string
      requestBody:
        content:
          application/vnd.hedtech.integration.v1.0.0+json:
            example:
              value:
                mandatoryInd: Y
                kbentryTermCode: '201410'
                id: '301718111'
      responses:
        '200':
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response
                body is associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/admissions-application-checklist-1.0.0_put'
        '401':
          description: Failure. Unauthorized
        '500':
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/errors-2.0.0'
    post:
      tags:
      - admissions-application-checklist
      summary: Creates a new resource in SAAADMS
      parameters:
      - name: limit
        in: query
        description: The maximum number of resources requesting for this result set.
        required: false
        schema:
          type: integer
      - name: offset
        in: query
        description: The 0 based index for a collection of resources for the page
          requested.
        required: false
        schema:
          type: integer
      - name: criteria
        in: query
        description: The filter criteria. Must be a JSON representation of the property
          searching for.  This can be any of the properties listed on the URL or QAPI
          and must be a json representation that can be validated against the GET
          schema.
        required: false
        schema:
          type: string
      - name: X-SDE-Expand
        in: header
        description: The comma seperated value list of block names
        required: false
        schema:
          type: string
      - name: id
        in: query
        required: false
        schema:
          type: string
      - name: kbentryTermCode
        in: query
        required: false
        schema:
          type: string
      - name: admrCode
        in: query
        required: true
        schema:
          type: string
      - name: receiveDate
        in: query
        required: false
        schema:
          type: string
      - name: codeValue
        in: query
        required: false
        schema:
          type: string
      - name: comment
        in: query
        required: false
        schema:
          type: string
      - name: mandatoryInd
        in: query
        required: false
        schema:
          type: string
      - name: printInd
        in: query
        required: false
        schema:
          type: string
      - name: reqDate1
        in: query
        required: false
        schema:
          type: string
      - name: reqDate2
        in: query
        required: false
        schema:
          type: string
      - name: deadlineDate
        in: query
        required: false
        schema:
          type: string
      - name: cksrCode
        in: query
        required: false
        schema:
          type: string
      requestBody:
        content:
          application/vnd.hedtech.integration.v1.0.0+json:
            example:
              value:
                admrCode: CLT1
                kbentryTermCode: '201410'
                cksrCode: BASELINE
                id: '301718111'
      responses:
        '200':
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response
                body is associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/admissions-application-checklist-1.0.0_post'
        '401':
          description: Failure. Unauthorized
        '500':
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/errors-2.0.0'
  /qapi/admissions-application-checklist:
    post:
      tags:
      - admissions-application-checklist QAPI (Query by POST)
      summary: Return resources from SAAADMS
      parameters:
      - name: content type
        in: header
        required: true
        content:
          application/vnd.hedtech.integration.v1.0.0+json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/admissions-application-checklist-1.0.0_qapi_post'
      requestBody:
        content:
          application/vnd.hedtech.integration.v1.0.0+json:
            example:
              value:
                admrCode: CLT1
                kbentryTermCode: '201410'
                cksrCode: BASELINE
                id: '301718111'
      responses:
        '200':
          description: OK
          headers:
            X-Media-Type:
              description: The full semantic version with the media type of the response
              schema:
                type: string
            X-STP-Code:
              description: If STP (MEP) is enabled, returns the MEP code the response
                body is associated to
              schema:
                type: string
            X-SDE-Enabled:
              description: If SDE is enabled for this page
              schema:
                type: string
          content:
            application/vnd.hedtech.integration.v1.0.0+json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/admissions-application-checklist-1.0.0_get'
        '401':
          description: Failure. Unauthorized
        '500':
          description: Error
          content:
            application/vnd.hedtech.integration.errors.v2+json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/errors-2.0.0'
components:
  schemas:
    admissions-application-checklist-1.0.0_put:
      required:
      - activityDate
      - admrCode
      type: object
      properties:
        reqCount:
          title: Count
          maxLength: 3
          type: number
          description: Lineage reference object of SARCHKL_REQ_COUNT
          x-lineageReferenceObject: SARCHKL_REQ_COUNT
        mandatoryInd:
          maxLength: 1
          type: string
          description: Lineage reference object of SARCHKL_MANDATORY_IND
          x-lineageReferenceObject: SARCHKL_MANDATORY_IND
        deadlineDate:
          title: Deadline
          maxLength: 11
          pattern: ^(-?(?:[1-9][0-9]*)?[0-9]{4})-(1[0-2]|0[1-9])-(3[0-1]|0[1-9]|[1-2][0-9])T(2[0-3]|[0-1][0-9]):([0-5][0-9]):([0-5][0-9])(\.[0-9]+)?(Z|[+-](?:2[0-3]|[0-1][0-9]):[0-5][0-9])?$
          type: number
          description: Lineage reference object of SARCHKL_DEADLINE_DATE
          x-lineageReferenceObject: SARCHKL_DEADLINE_DATE
        cksrCode:
          title: Checklist Origin
          maxLength: 15
          type: string
          description: Lineage reference object of SARCHKL_CKSR_CODE, Lookup lineage
            reference object of stvcksr
          x-lineageReferenceObject: SARCHKL_CKSR_CODE
          x-lineageLookupReferenceObject: stvcksr
        printInd:
          maxLength: 1
          type: string
          description: Lineage reference object of SARCHKL_PRINT_IND
          x-lineageReferenceObject: SARCHKL_PRINT_IND
        receiveDate:
          title: Received Date
          maxLength: 11
          pattern: ^(-?(?:[1-9][0-9]*)?[0-9]{4})-(1[0-2]|0[1-9])-(3[0-1]|0[1-9]|[1-2][0-9])T(2[0-3]|[0-1][0-9]):([0-5][0-9]):([0-5][0-9])(\.[0-9]+)?(Z|[+-](?:2[0-3]|[0-1][0-9]):[0-5][0-9])?$
          type: number
          description: Lineage reference object of SARCHKL_RECEIVE_DATE
          x-lineageReferenceObject: SARCHKL_RECEIVE_DATE
        source:
          maxLength: 30
          type: string
          description: Lineage reference object of SARCHKL_SOURCE
          x-lineageReferenceObject: SARCHKL_SOURCE
        userId:
          maxLength: 30
          type: string
          description: Lineage reference object of SARCHKL_USER_ID
          x-lineageReferenceObject: SARCHKL_USER_ID
        codeValue:
          title: Item
          maxLength: 10
          type: string
          description: Lineage reference object of SARCHKL_CODE_VALUE
          x-lineageReferenceObject: SARCHKL_CODE_VALUE
        sourceDate:
          title: Date
          maxLength: 11
          pattern: ^(-?(?:[1-9][0-9]*)?[0-9]{4})-(1[0-2]|0[1-9])-(3[0-1]|0[1-9]|[1-2][0-9])T(2[0-3]|[0-1][0-9]):([0-5][0-9]):([0-5][0-9])(\.[0-9]+)?(Z|[+-](?:2[0-3]|[0-1][0-9]):[0-5][0-9])?$
          type: number
          description: Lineage reference object of SARCHKL_SOURCE_DATE
          x-lineageReferenceObject: SARCHKL_SOURCE_DATE
        admrCode:
          title: Admission Request
          maxLength: 30
          type: string
          description: Lineage reference object of SARCHKL_ADMR_CODE, Lookup lineage
            reference object of stvadmr
          x-lineageReferenceObject: SARCHKL_ADMR_CODE
          x-lineageLookupReferenceObject: stvadmr
        activityDate:
          maxLength: 11
          pattern: ^(-?(?:[1-9][0-9]*)?[0-9]{4})-(1[0-2]|0[1-9])-(3[0-1]|0[1-9]|[1-2][0-9])T(2[0-3]|[0-1][0-9]):([0-5][0-9]):([0-5][0-9])(\.[0-9]+)?(Z|[+-](?:2[0-3]|[0-1][0-9]):[0-5][0-9])?$
          type: number
          description: Lineage reference object of SARCHKL_ACTIVITY_DATE
          x-lineageReferenceObject: SARCHKL_ACTIVITY_DATE
        ckstCode:
          title: Status
          maxLength: 30
          type: string
          description: Lineage reference object of SARCHKL_CKST_CODE, Lookup lineage
            reference object of stvckst
          x-lineageReferenceObject: SARCHKL_CKST_CODE
          x-lineageLookupReferenceObject: stvckst
        stvadmrDesc:
          title: Description
          type: string
        comment:
          title: Item Description
          maxLength: 60
          type: string
          description: Lineage reference object of SARCHKL_COMMENT
          x-lineageReferenceObject: SARCHKL_COMMENT
        reqDate2:
          title: Last Request
          maxLength: 11
          pattern: ^(-?(?:[1-9][0-9]*)?[0-9]{4})-(1[0-2]|0[1-9])-(3[0-1]|0[1-9]|[1-2][0-9])T(2[0-3]|[0-1][0-9]):([0-5][0-9]):([0-5][0-9])(\.[0-9]+)?(Z|[+-](?:2[0-3]|[0-1][0-9]):[0-5][0-9])?$
          type: number
          description: Lineage reference object of SARCHKL_REQ_DATE2
          x-lineageReferenceObject: SARCHKL_REQ_DATE2
        reqDate1:
          title: First Request
          maxLength: 11
          pattern: ^(-?(?:[1-9][0-9]*)?[0-9]{4})-(1[0-2]|0[1-9])-(3[0-1]|0[1-9]|[1-2][0-9])T(2[0-3]|[0-1][0-9]):([0-5][0-9]):([0-5][0-9])(\.[0-9]+)?(Z|[+-](?:2[0-3]|[0-1][0-9]):[0-5][0-9])?$
          type: number
          description: Lineage reference object of SARCHKL_REQ_DATE1
          x-lineageReferenceObject: SARCHKL_REQ_DATE1
      additionalProperties: false
      x-lineageReferenceObject: sarchkl
    errors-2.0.0:
      required:
      - errors
      type: object
      properties:
        errors:
          type: array
          items:
            type: object
            properties:
              message:
                type: string
              description:
                type: string
    admissions-application-checklist-1.0.0_qapi_post:
      type: object
      properties:
        id:
          type: string
        kbentryTermCode:
          type: string
    admissions-application-checklist-1.0.0_get:
      required:
      - activityDate
      - admrCode
      type: object
      properties:
        reqCount:
          title: Count
          maxLength: 3
          type: number
          description: Lineage reference object of SARCHKL_REQ_COUNT
          x-lineageReferenceObject: SARCHKL_REQ_COUNT
        mandatoryInd:
          maxLength: 1
          type: string
          description: Lineage reference object of SARCHKL_MANDATORY_IND
          x-lineageReferenceObject: SARCHKL_MANDATORY_IND
        deadlineDate:
          title: Deadline
          maxLength: 11
          pattern: ^(-?(?:[1-9][0-9]*)?[0-9]{4})-(1[0-2]|0[1-9])-(3[0-1]|0[1-9]|[1-2][0-9])T(2[0-3]|[0-1][0-9]):([0-5][0-9]):([0-5][0-9])(\.[0-9]+)?(Z|[+-](?:2[0-3]|[0-1][0-9]):[0-5][0-9])?$
          type: number
          description: Lineage reference object of SARCHKL_DEADLINE_DATE
          x-lineageReferenceObject: SARCHKL_DEADLINE_DATE
        cksrCode:
          title: Checklist Origin
          maxLength: 15
          type: string
          description: Lineage reference object of SARCHKL_CKSR_CODE, Lookup lineage
            reference object of stvcksr
          x-lineageReferenceObject: SARCHKL_CKSR_CODE
          x-lineageLookupReferenceObject: stvcksr
        printInd:
          maxLength: 1
          type: string
          description: Lineage reference object of SARCHKL_PRINT_IND
          x-lineageReferenceObject: SARCHKL_PRINT_IND
        receiveDate:
          title: Received Date
          maxLength: 11
          pattern: ^(-?(?:[1-9][0-9]*)?[0-9]{4})-(1[0-2]|0[1-9])-(3[0-1]|0[1-9]|[1-2][0-9])T(2[0-3]|[0-1][0-9]):([0-5][0-9]):([0-5][0-9])(\.[0-9]+)?(Z|[+-](?:2[0-3]|[0-1][0-9]):[0-5][0-9])?$
          type: number
          description: Lineage reference object of SARCHKL_RECEIVE_DATE
          x-lineageReferenceObject: SARCHKL_RECEIVE_DATE
        source:
          maxLength: 30
          type: string
          description: Lineage reference object of SARCHKL_SOURCE
          x-lineageReferenceObject: SARCHKL_SOURCE
        userId:
          maxLength: 30
          type: string
          description: Lineage reference object of SARCHKL_USER_ID
          x-lineageReferenceObject: SARCHKL_USER_ID
        codeValue:
          title: Item
          maxLength: 10
          type: string
          description: Lineage reference object of SARCHKL_CODE_VALUE
          x-lineageReferenceObject: SARCHKL_CODE_VALUE
        sourceDate:
          title: Date
          maxLength: 11
          pattern: ^(-?(?:[1-9][0-9]*)?[0-9]{4})-(1[0-2]|0[1-9])-(3[0-1]|0[1-9]|[1-2][0-9])T(2[0-3]|[0-1][0-9]):([0-5][0-9]):([0-5][0-9])(\.[0-9]+)?(Z|[+-](?:2[0-3]|[0-1][0-9]):[0-5][0-9])?$
          type: number
          description: Lineage reference object of SARCHKL_SOURCE_DATE
          x-lineageReferenceObject: SARCHKL_SOURCE_DATE
        admrCode:
          title: Admission Request
          maxLength: 30
          type: string
          description: Lineage reference object of SARCHKL_ADMR_CODE, Lookup lineage
            reference object of stvadmr
          x-lineageReferenceObject: SARCHKL_ADMR_CODE
          x-lineageLookupReferenceObject: stvadmr
        activityDate:
          maxLength: 11
          pattern: ^(-?(?:[1-9][0-9]*)?[0-9]{4})-(1[0-2]|0[1-9])-(3[0-1]|0[1-9]|[1-2][0-9])T(2[0-3]|[0-1][0-9]):([0-5][0-9]):([0-5][0-9])(\.[0-9]+)?(Z|[+-](?:2[0-3]|[0-1][0-9]):[0-5][0-9])?$
          type: number
          description: Lineage reference object of SARCHKL_ACTIVITY_DATE
          x-lineageReferenceObject: SARCHKL_ACTIVITY_DATE
        ckstCode:
          title: Status
          maxLength: 30
          type: string
          description: Lineage reference object of SARCHKL_CKST_CODE, Lookup lineage
            reference object of stvckst
          x-lineageReferenceObject: SARCHKL_CKST_CODE
          x-lineageLookupReferenceObject: stvckst
        stvadmrDesc:
          title: Description
          type: string
        comment:
          title: Item Description
          maxLength: 60
          type: string
          description: Lineage reference object of SARCHKL_COMMENT
          x-lineageReferenceObject: SARCHKL_COMMENT
        reqDate2:
          title: Last Request
          maxLength: 11
          pattern: ^(-?(?:[1-9][0-9]*)?[0-9]{4})-(1[0-2]|0[1-9])-(3[0-1]|0[1-9]|[1-2][0-9])T(2[0-3]|[0-1][0-9]):([0-5][0-9]):([0-5][0-9])(\.[0-9]+)?(Z|[+-](?:2[0-3]|[0-1][0-9]):[0-5][0-9])?$
          type: number
          description: Lineage reference object of SARCHKL_REQ_DATE2
          x-lineageReferenceObject: SARCHKL_REQ_DATE2
        reqDate1:
          title: First Request
          maxLength: 11
          pattern: ^(-?(?:[1-9][0-9]*)?[0-9]{4})-(1[0-2]|0[1-9])-(3[0-1]|0[1-9]|[1-2][0-9])T(2[0-3]|[0-1][0-9]):([0-5][0-9]):([0-5][0-9])(\.[0-9]+)?(Z|[+-](?:2[0-3]|[0-1][0-9]):[0-5][0-9])?$
          type: number
          description: Lineage reference object of SARCHKL_REQ_DATE1
          x-lineageReferenceObject: SARCHKL_REQ_DATE1
      additionalProperties: false
      x-lineageReferenceObject: sarchkl
    admissions-application-checklist-1.0.0_post:
      required:
      - activityDate
      - admrCode
      type: object
      properties:
        reqCount:
          title: Count
          maxLength: 3
          type: number
          description: Lineage reference object of SARCHKL_REQ_COUNT
          x-lineageReferenceObject: SARCHKL_REQ_COUNT
        mandatoryInd:
          maxLength: 1
          type: string
          description: Lineage reference object of SARCHKL_MANDATORY_IND
          x-lineageReferenceObject: SARCHKL_MANDATORY_IND
        deadlineDate:
          title: Deadline
          maxLength: 11
          pattern: ^(-?(?:[1-9][0-9]*)?[0-9]{4})-(1[0-2]|0[1-9])-(3[0-1]|0[1-9]|[1-2][0-9])T(2[0-3]|[0-1][0-9]):([0-5][0-9]):([0-5][0-9])(\.[0-9]+)?(Z|[+-](?:2[0-3]|[0-1][0-9]):[0-5][0-9])?$
          type: number
          description: Lineage reference object of SARCHKL_DEADLINE_DATE
          x-lineageReferenceObject: SARCHKL_DEADLINE_DATE
        cksrCode:
          title: Checklist Origin
          maxLength: 15
          type: string
          description: Lineage reference object of SARCHKL_CKSR_CODE, Lookup lineage
            reference object of stvcksr
          x-lineageReferenceObject: SARCHKL_CKSR_CODE
          x-lineageLookupReferenceObject: stvcksr
        printInd:
          maxLength: 1
          type: string
          description: Lineage reference object of SARCHKL_PRINT_IND
          x-lineageReferenceObject: SARCHKL_PRINT_IND
        receiveDate:
          title: Received Date
          maxLength: 11
          pattern: ^(-?(?:[1-9][0-9]*)?[0-9]{4})-(1[0-2]|0[1-9])-(3[0-1]|0[1-9]|[1-2][0-9])T(2[0-3]|[0-1][0-9]):([0-5][0-9]):([0-5][0-9])(\.[0-9]+)?(Z|[+-](?:2[0-3]|[0-1][0-9]):[0-5][0-9])?$
          type: number
          description: Lineage reference object of SARCHKL_RECEIVE_DATE
          x-lineageReferenceObject: SARCHKL_RECEIVE_DATE
        source:
          maxLength: 30
          type: string
          description: Lineage reference object of SARCHKL_SOURCE
          x-lineageReferenceObject: SARCHKL_SOURCE
        userId:
          maxLength: 30
          type: string
          description: Lineage reference object of SARCHKL_USER_ID
          x-lineageReferenceObject: SARCHKL_USER_ID
        codeValue:
          title: Item
          maxLength: 10
          type: string
          description: Lineage reference object of SARCHKL_CODE_VALUE
          x-lineageReferenceObject: SARCHKL_CODE_VALUE
        sourceDate:
          title: Date
          maxLength: 11
          pattern: ^(-?(?:[1-9][0-9]*)?[0-9]{4})-(1[0-2]|0[1-9])-(3[0-1]|0[1-9]|[1-2][0-9])T(2[0-3]|[0-1][0-9]):([0-5][0-9]):([0-5][0-9])(\.[0-9]+)?(Z|[+-](?:2[0-3]|[0-1][0-9]):[0-5][0-9])?$
          type: number
          description: Lineage reference object of SARCHKL_SOURCE_DATE
          x-lineageReferenceObject: SARCHKL_SOURCE_DATE
        admrCode:
          title: Admission Request
          maxLength: 30
          type: string
          description: Lineage reference object of SARCHKL_ADMR_CODE, Lookup lineage
            reference object of stvadmr
          x-lineageReferenceObject: SARCHKL_ADMR_CODE
          x-lineageLookupReferenceObject: stvadmr
        activityDate:
          maxLength: 11
          pattern: ^(-?(?:[1-9][0-9]*)?[0-9]{4})-(1[0-2]|0[1-9])-(3[0-1]|0[1-9]|[1-2][0-9])T(2[0-3]|[0-1][0-9]):([0-5][0-9]):([0-5][0-9])(\.[0-9]+)?(Z|[+-](?:2[0-3]|[0-1][0-9]):[0-5][0-9])?$
          type: number
          description: Lineage reference object of SARCHKL_ACTIVITY_DATE
          x-lineageReferenceObject: SARCHKL_ACTIVITY_DATE
        ckstCode:
          title: Status
          maxLength: 30
          type: string
          description: Lineage reference object of SARCHKL_CKST_CODE, Lookup lineage
            reference object of stvckst
          x-lineageReferenceObject: SARCHKL_CKST_CODE
          x-lineageLookupReferenceObject: stvckst
        stvadmrDesc:
          title: Description
          type: string
        comment:
          title: Item Description
          maxLength: 60
          type: string
          description: Lineage reference object of SARCHKL_COMMENT
          x-lineageReferenceObject: SARCHKL_COMMENT
        reqDate2:
          title: Last Request
          maxLength: 11
          pattern: ^(-?(?:[1-9][0-9]*)?[0-9]{4})-(1[0-2]|0[1-9])-(3[0-1]|0[1-9]|[1-2][0-9])T(2[0-3]|[0-1][0-9]):([0-5][0-9]):([0-5][0-9])(\.[0-9]+)?(Z|[+-](?:2[0-3]|[0-1][0-9]):[0-5][0-9])?$
          type: number
          description: Lineage reference object of SARCHKL_REQ_DATE2
          x-lineageReferenceObject: SARCHKL_REQ_DATE2
        reqDate1:
          title: First Request
          maxLength: 11
          pattern: ^(-?(?:[1-9][0-9]*)?[0-9]{4})-(1[0-2]|0[1-9])-(3[0-1]|0[1-9]|[1-2][0-9])T(2[0-3]|[0-1][0-9]):([0-5][0-9]):([0-5][0-9])(\.[0-9]+)?(Z|[+-](?:2[0-3]|[0-1][0-9]):[0-5][0-9])?$
          type: number
          description: Lineage reference object of SARCHKL_REQ_DATE1
          x-lineageReferenceObject: SARCHKL_REQ_DATE1
      additionalProperties: false
      x-lineageReferenceObject: sarchkl
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer